### PR TITLE
Feat/amazonia 1

### PR DESCRIPTION
**Pull request by wildintellect**
New notebook demonstrating how to query and access data from the Amazonia-1 WFI sensor with `stackstac`.

### CODE REVIEW

**Comment by wildintellect** [comment]
I realized I forgot to update the readme. Working on that.
Also need to look into RGB adjustments with colormap for more True color rendering.

**Comment by wildintellect** [comment]
<p>Hmm, I don't think this example uses rio-tiler must be left over from the prior example.</p>

---

 <a href='https://app.reviewnb.com/developmentseed/asdi-examples/pull/12/discussion/#comment-1735842416'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>that is best practices, I'll do that.</p>

---

 <a href='https://app.reviewnb.com/developmentseed/asdi-examples/pull/12/discussion/#comment-1735842436'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>if this wasn't a notebook I'd probably agree. going to leave as is for now. came directly from other examples online and more clearly shows the shapely library.</p>

---

 <a href='https://app.reviewnb.com/developmentseed/asdi-examples/pull/12/discussion/#comment-1735842510'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>STAC-Item?</p>

---

 <a href='https://app.reviewnb.com/developmentseed/asdi-examples/pull/12/discussion/#comment-1735842543'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>also it's not a DEM ...</p>

---

 <a href='https://app.reviewnb.com/developmentseed/asdi-examples/pull/12/discussion/#comment-1735842616'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jjfrench** [comment]
<p>I think this is the last change I would make. The other conversations seem to be resolved.</p>

---

 <a href='https://app.reviewnb.com/developmentseed/asdi-examples/pull/12/discussion/#comment-1735842476'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>Ah TitleCase instead of a sentence ... I might want to change the title entirely to something like <code>Overview Map for Context</code> what do you think of this title? </p>

---

 <a href='https://app.reviewnb.com/developmentseed/asdi-examples/pull/12/discussion/#comment-1735842476'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jjfrench** [comment]
<p>I like that 👍🏻</p>

---

 <a href='https://app.reviewnb.com/developmentseed/asdi-examples/pull/12/discussion/#comment-1735842476'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by jjfrench — APPROVED** [review]

**Pull request merged**
